<a href="https://colab.research.google.com/github/hby1117/class2026Spring/blob/main/04_Pandas_Practice_Answers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<a href="https://colab.research.google.com/github/hby1117/class2026Spring/blob/main/04_Pandas_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas Practice

In [1]:
import pandas as pd

dfw = pd.read_csv("weather.csv")
dfp = pd.read_csv("product.csv")
dfm = pd.read_csv("movies.csv")

## Part 1. Weather

1. Temperature column

In [2]:
dfw["Temperature"]

0    22.2
1    20.0
2    18.3
3    23.9
4    21.1
Name: Temperature, dtype: float64

2. Humidity와 City column

In [3]:
dfw[["Humidity", "City"]]

   Humidity         City
0        30     New York
1        50  Los Angeles
2        45      Chicago
3        35      Houston
4        40      Phoenix

3. 0번 row

In [4]:
dfw.loc[0]

Temperature        22.2
Humidity             30
City           New York
Name: 0, dtype: object

4. 1~3번 row

In [5]:
dfw.loc[1:3]

   Temperature  Humidity         City
1         20.0        50  Los Angeles
2         18.3        45      Chicago
3         23.9        35      Houston

5. Temperature이 21보다 높은 row

In [6]:
cond = dfw["Temperature"] > 21
dfw[cond]

   Temperature  Humidity      City
0         22.2        30  New York
3         23.9        35   Houston
4         21.1        40   Phoenix

6. Humidity가 40 이상인 row

In [7]:
cond = dfw["Humidity"] >= 40
dfw[cond]

   Temperature  Humidity         City
1         20.0        50  Los Angeles
2         18.3        45      Chicago
4         21.1        40      Phoenix

7. Temperature가 21보다 크고 Humidity가 40보다 작은 row

In [8]:
cond = (dfw["Temperature"] > 21) & (dfw["Humidity"] < 40)
dfw[cond]

   Temperature  Humidity      City
0         22.2        30  New York
3         23.9        35   Houston

## Part 2. Product

1. Price column

In [9]:
dfp["Price"]

0    0.85
1    0.65
2    0.50
3    1.50
4    0.90
5    0.55
Name: Price, dtype: float64

2. Category와 Item column

In [10]:
dfp[["Category", "Item"]]

    Category    Item
0      Fruit   Apple
1      Fruit  Banana
2  Vegetable  Carrot
3  Vegetable    Bean
4      Fruit   Apple
5  Vegetable  Carrot

3. 0번 row

In [11]:
dfp.loc[0]

Category    Fruit
Item        Apple
Price        0.85
Quantity       50
Name: 0, dtype: object

4. 1번~4번 row

In [12]:
dfp.loc[1:4]

    Category    Item  Price  Quantity
1      Fruit  Banana   0.65        60
2  Vegetable  Carrot   0.50        70
3  Vegetable    Bean   1.50        40
4      Fruit   Apple   0.90        55

5. Price가 1 이상인 row

In [13]:
dfp[dfp["Price"] >= 1]

    Category  Item  Price  Quantity
3  Vegetable  Bean    1.5        40

6. Quantity가 60 이상인 row

In [14]:
cond = dfp["Quantity"] >= 60
dfp[cond]

    Category    Item  Price  Quantity
1      Fruit  Banana   0.65        60
2  Vegetable  Carrot   0.50        70
5  Vegetable  Carrot   0.55        75

7. Category가 "Fruit"이고 Quantity가 50보다 큰 row

In [15]:
cond = (dfp["Category"] == "Fruit") & (dfp["Quantity"] > 50)
dfp[cond]

  Category    Item  Price  Quantity
1    Fruit  Banana   0.65        60
4    Fruit   Apple   0.90        55

8. Category가 'Vegetable'이고 Price가 1보다 작은 row

In [16]:
cond = (dfp["Category"] == "Vegetable") & (dfp["Price"] < 1)
dfp[cond]

    Category    Item  Price  Quantity
2  Vegetable  Carrot   0.50        70
5  Vegetable  Carrot   0.55        75

9. Category별 평균 Price

In [17]:
dfp.groupby("Category")["Price"].mean()

Category
Fruit        0.80
Vegetable    0.85
Name: Price, dtype: float64

10. Category별 평균 Quantity

In [18]:
dfp.groupby("Category")["Quantity"].mean()

Category
Fruit        55.000000
Vegetable    61.666667
Name: Quantity, dtype: float64

11. Category별 최대 Quantity

In [19]:
dfp.groupby("Category")["Quantity"].max()

Category
Fruit        60
Vegetable    75
Name: Quantity, dtype: int64

12. Quantity가 평균보다 큰 row

In [20]:
# dfp["Quantity"].mean()은 전체 row에서 Quantity의 평균입니다.

cond = dfp["Quantity"] > dfp["Quantity"].mean()
dfp[cond]

    Category    Item  Price  Quantity
1      Fruit  Banana   0.65        60
2  Vegetable  Carrot   0.50        70
5  Vegetable  Carrot   0.55        75

## Part 3. Movies

1. Title column

In [21]:
dfm["Title"]

0    Inception
1      Titanic
2       Avatar
3       Frozen
4        Joker
5    Toy Story
6     Avengers
7       Matrix
8    Gladiator
9         Coco
Name: Title, dtype: object

2. Genre와 Rating column

In [22]:
dfm[["Genre", "Rating"]]

       Genre  Rating
0     Sci-Fi     8.8
1    Romance     7.8
2     Sci-Fi     7.9
3  Animation     7.5
4      Drama     8.4
5  Animation     8.3
6     Action     8.0
7     Sci-Fi     8.7
8     Action     8.5
9  Animation     8.4

3. 2번 row

In [23]:
dfm.loc[2]

Title     Avatar
Genre     Sci-Fi
Year        2009
Rating       7.9
Views        180
Name: 2, dtype: object

4. 2~3번 row

In [24]:
dfm.loc[2:3]

    Title      Genre  Year  Rating  Views
2  Avatar     Sci-Fi  2009     7.9    180
3  Frozen  Animation  2013     7.5    220

5. Rating이 8 이상인 row

In [25]:
cond = dfm["Rating"] >= 8
dfm[cond]

       Title      Genre  Year  Rating  Views
0  Inception     Sci-Fi  2010     8.8    150
4      Joker      Drama  2019     8.4    170
5  Toy Story  Animation  1995     8.3    160
6   Avengers     Action  2012     8.0    210
7     Matrix     Sci-Fi  1999     8.7    190
8  Gladiator     Action  2000     8.5    140
9       Coco  Animation  2017     8.4    130

6. Views가 180 이상인 row

In [26]:
cond = dfm["Views"] >= 180
dfm[cond]

      Title      Genre  Year  Rating  Views
1   Titanic    Romance  1997     7.8    200
2    Avatar     Sci-Fi  2009     7.9    180
3    Frozen  Animation  2013     7.5    220
6  Avengers     Action  2012     8.0    210
7    Matrix     Sci-Fi  1999     8.7    190

7. Genre가 'Sci-Fi'이고 Rating이 8보다 큰 row

In [27]:
cond = (dfm["Genre"] == "Sci-Fi") & (dfm["Rating"] > 8)
dfm[cond]

       Title   Genre  Year  Rating  Views
0  Inception  Sci-Fi  2010     8.8    150
7     Matrix  Sci-Fi  1999     8.7    190

8. Genre가 'Animation'이고 Views가 150보다 큰 row

In [28]:
cond = (dfm["Genre"] == "Animation") & (dfm["Views"] > 150)
dfm[cond]

       Title      Genre  Year  Rating  Views
3     Frozen  Animation  2013     7.5    220
5  Toy Story  Animation  1995     8.3    160

9. Genre별 평균 Rating

In [29]:
dfm.groupby("Genre")["Rating"].mean()

Genre
Action       8.250000
Animation    8.066667
Drama        8.400000
Romance      7.800000
Sci-Fi       8.466667
Name: Rating, dtype: float64

10. Genre별 평균 Views

In [30]:
dfm.groupby("Genre")["Views"].mean()

Genre
Action       175.000000
Animation    170.000000
Drama        170.000000
Romance      200.000000
Sci-Fi       173.333333
Name: Views, dtype: float64

11. Genre별 최대 Rating

In [31]:
dfm.groupby("Genre")["Rating"].max()

Genre
Action       8.5
Animation    8.4
Drama        8.4
Romance      7.8
Sci-Fi       8.8
Name: Rating, dtype: float64

12. Rating이 평균보다 높은 row

In [32]:
# dfm["Rating"].mean()은 전체 row에서 Rating의 평균입니다.

cond = dfm["Rating"] > dfm["Rating"].mean()
dfm[cond]

       Title      Genre  Year  Rating  Views
0  Inception     Sci-Fi  2010     8.8    150
4      Joker      Drama  2019     8.4    170
5  Toy Story  Animation  1995     8.3    160
7     Matrix     Sci-Fi  1999     8.7    190
8  Gladiator     Action  2000     8.5    140
9       Coco  Animation  2017     8.4    130